### ISSUE TITLE
Panels layouts

### ISSUE THREAD

**Issue by tieugene** [Axel-Erfurt/QFilemanager#2]
Proposition: switch layouts to modes (like [XFE](http://roland65.free.fr/xfe/)):
* Files only (1 panel)
* Tree+Files (2 panels; QFileManager now)
* 2xFiles (2 panels; QFileManagerDouble now)
* Tree+2xFiles (3 panels)

**Comment by Axel-Erfurt** [comment]
If you need that then you can add it.
